### ISSUE TITLE
[Website] Api url always use server url

### ISSUE THREAD

**Issue by Niteletsplay** [seekr-osint/seekr#265]

**Comment by 9glenda** [comment]
![image](https://user-images.githubusercontent.com/69043370/232340590-f1793d34-fb5b-4e57-bfc3-9cefdb76aa93.png)

**Comment by 9glenda** [comment]
without any javascript issues

**Comment by 9glenda** [comment]
This breaks compatibility with the legacy live server on 5050 which is still started by seekr. Are you using the legacy live server on 5050 @Niteletsplay ? is compatibility with it still needed? should we even still start it?

**Comment by 9glenda** [comment]
![IMG_20230416_225939](https://user-images.githubusercontent.com/69043370/232341921-fcbe1df2-a470-4d80-84a3-056bb0071358.jpg)
@Niteletsplay with this being merged mobile is supported but the design isn't responisve. ;)
