### ISSUE TITLE
[WEBSITE BUG]

### ISSUE THREAD

**Issue by sudzu87dn** [seekr-osint/seekr#303]
![error_seekr](https://user-images.githubusercontent.com/70649556/232991641-a0632815-3e19-471c-b64e-bcf8a13a8f42.png)
"The requested URL was not found on this server".
i got this issue with web server, pls help me!

**Comment by Niteletsplay** [comment]
Hello! Could you tell me the specifics? Like seekr version, browser and os?

**Comment by sudzu87dn** [comment]
> Hello! Could you tell me the specifics? Like seekr version, browser and os?

i just clone seekr yesterday to my Git on Window11, my browser is Crome v112.0.5615.122
everything ok, but after go run main.go, http://localhost:8080/web/index.html error seen,

**Comment by Niteletsplay** [comment]
Try using the latest release .exe [here](github.com/seekr-osint/seekr/releases/latest)

**Comment by Niteletsplay** [comment]
Its also possible that apache (which we, to my knowledge, dont use for seekr) conflicts with the ports. We are currently working on the ability to configure the port in #295

**Comment by sudzu87dn** [comment]
8080 is my free port, i configed apache use 8080 already, but still not work
![port_seekr1](https://user-images.githubusercontent.com/70649556/233022971-9249ca76-a0e2-4ae2-9deb-9237d5f4e89a.png)

**Comment by Niteletsplay** [comment]
Try using 8081 for seekr

**Comment by 9glenda** [comment]
It appears apatche is running on 8080. Could you send the output of this command?
```
go run main.go --port=818

```

**Comment by sudzu87dn** [comment]
> It appears apatche is running on 8080. Could you send the output of this command?
> 
> ```
> go run main.go --port=818
> ```

![port_seekr1](https://user-images.githubusercontent.com/70649556/233024228-cfd05af5-e672-4ad6-aca7-64b3ef7b4b17.png)
:(

**Comment by 9glenda** [comment]
Oh I'm sorry its 
```
go run apiPort=8181
```

**Comment by 9glenda** [comment]
What the hell

**Comment by 9glenda** [comment]
Do it in powershell

**Comment by 9glenda** [comment]
```
go run --apiPort=8181
```

**Comment by 9glenda** [comment]
Sorry by bad

**Comment by 9glenda** [comment]
```
go run main.go --apiPort=8181
```

**Comment by 9glenda** [comment]
This issue will be addressed and fixed in #304

**Comment by sudzu87dn** [comment]
> ```
> go run main.go --apiPort=8181
> ```

![error_seekr2](https://user-images.githubusercontent.com/70649556/233026846-cc8e7ed9-1ae0-4212-aac1-450e3f33b971.png)

**Comment by 9glenda** [comment]
Send the output of the command

**Comment by sudzu87dn** [comment]
> Try
> 
> ```batchfile
> git pull
> go run main.go
> ```
> 
> We got a hotfix merged into main

![error_seekr3](https://user-images.githubusercontent.com/70649556/233032576-d0747ac6-bf15-4431-b32e-2e7ce26f6a39.png)
![error_seekr4](https://user-images.githubusercontent.com/70649556/233032583-21a60547-3c02-4033-8eeb-2ee85268a7ba.png)
![error_seekr5](https://user-images.githubusercontent.com/70649556/233032588-726038ac-7ac3-4c99-b771-ee713e2459e0.png)

**Comment by 9glenda** [comment]
You wanna hopp into a call? I think that's a bigger issue easier to resolve in a call.

**Comment by Niteletsplay** [comment]
https://meet.jit.si/seekr-talk

**Comment by 9glenda** [comment]
Try reloading the site

**Comment by sudzu87dn** [comment]
> You wanna hop into a call? I think that's a bigger issue easier to resolve in a call.

can u help me over anydesk? :)

**Comment by 9glenda** [comment]
Sure. If you could leave a discord tag or something that would be useful.

**Comment by sudzu87dn** [comment]
> Sure. If you could leave a discord tag or something that would be useful.

sr, i dont use discord, cant u remote and see in my comp? do u use tele, viber or whatapp?

**Comment by 9glenda** [comment]
@P75552669

**Comment by sudzu87dn** [comment]
> Telegram: http://t.me/P75552669

**Comment by Niteletsplay** [comment]
Resolved by pulling and and deleting database folder

**Comment by sudzu87dn** [comment]
> Resolved by pulling and and deleting database folder

yep, it work! tks u so much, bro!
