### ISSUE TITLE
[Website] Remove & change useless & rarely used fields

### ISSUE THREAD

**Issue by Niteletsplay** [seekr-osint/seekr#311]
### Delete (Had to be done in #306 due to structural changes, documented here)

- [X] SSN
- [X] Maiden name
- [X] Military stand

### Change
- [x] Club --> Becomes similar to Email to allow for multiple clubs
- [x] Hobbies --> Becomes similar to Email to allow for multiple hobbies
- [x] Religion --> Dropdown
- [x] Civil status --> Dropdown

**Comment by 9glenda** [comment]
```go
package club

// Club

// Types
type Clubs map[string]Club
type Club struct {
  Club string `json:"Club"`
}
```
