### ISSUE TITLE
[Website] Type Script because Java Script sucks

### ISSUE THREAD

**Issue by 9glenda** [seekr-osint/seekr#344]

**Comment by Niteletsplay** [comment]
Do we close this as wontfix?

**Comment by Niteletsplay** [comment]
```
tsc --project web
```
Can be used to compile typescript from the main folder

**Comment by Niteletsplay** [comment]
> Is there a flag for turning of watch since for just compiling seekr it doesn’t make sense to have the tsc command running forever.

```
tsc --project web --watch false
```

**Comment by Niteletsplay** [comment]
Converted by now:

- [ ] framework.js
- [ ] guide.js
- [ ] Unfinished tempmail.js
- [ ] settings.js
- [ ] script.js

script.js

- [ ] view
- [ ] edit
- [ ] create
