### ISSUE TITLE
[API BUG]Instagram Twitter and HTB false positives/negatives

### ISSUE THREAD

**Issue by tuxorials2** [seekr-osint/seekr#498]
Instagram is false negativing
Twitter is giving false positives
and so is HackTheBox out of all things
Please get this fixed asap so i can more easily stalk my friends (I'm kidding)
I'll look if I can find the bugs myself and then may let you know or fix it myself.

**Comment by Niteletsplay** [comment]
@9glenda Can you help here?

**Comment by Niteletsplay** [comment]
Currently working on this.
Heres my current progress:

False positives:
- TryHackMe
- Twitter
- HackTheBox

False negatives:
- Instagram
