### ISSUE TITLE
Webserver started but page only containing '{}' [Website]

### ISSUE THREAD

**Issue by anoo2niem** [seekr-osint/seekr#499]
Hi, 

First of al, i'm a noob, so forgive me please if this issue is stupid :)

I've never done osint, but came across this tool, and wanted to try it, as it would be a nice addition to my proxmox server.

I created a new lxc container (debian 12) , installed golang (go version go1.20.6 linux/amd64).

I've followed the instructions provided to get seekr running (unstable).

wget 'path' > cd seekr > go run main.go

I've got 2 errors, first one was that ~/.config/seekr/config.toml file could not be found, and second some xdg-open error.
I've looked here in the issues and i could find an example of the config.toml file.

I manually placed it there `[server]
ip = "0.0.0.0"
port = 8080
[general]
browser = true`

I installed xdg-utils aswell. 

Ran again and both errors gone, webserver starting but the output of the website is just '{}'.

I've pulled 0.3.6.tar.gz aswell and tried it this way, but same issue; webserver running, output '{}'

I guess the fact that i had to create the config.toml file myself, is part of where the issue is...

Any help to set this up properly would be appreciated.

Thanks in advance.

**Comment by anoo2niem** [comment]
Hey, 

Thanks! 
The webinterface is loading now by using /web at the end of the url.

However, not fully functional.
The some .js files are not loading (404)

`[GIN] 2023/07/20 - 11:54:24 | 200 |    2.326465ms |    192.168.1.17 | GET      "/web/"
[GIN] 2023/07/20 - 11:54:25 | 200 |       9.974µs |    192.168.1.17 | GET      "/web/css/hub.css"
[GIN] 2023/07/20 - 11:54:25 | 200 |      70.116µs |    192.168.1.17 | GET      "/web/css/style.css"
[GIN] 2023/07/20 - 11:54:25 | 404 |      17.162µs |    192.168.1.17 | GET      "/web/dist/ts/theme_loader.js"
[GIN] 2023/07/20 - 11:54:25 | 404 |      35.061µs |    192.168.1.17 | GET      "/web/dist/ts/translate.js"
[GIN] 2023/07/20 - 11:54:25 | 404 |      10.185µs |    192.168.1.17 | GET      "/web/dist/ts/easteregg.js"
[GIN] 2023/07/20 - 11:54:25 | 200 |       59.11µs |    192.168.1.17 | GET      "/web/images/favicon.ico"
[GIN] 2023/07/20 - 11:54:26 | 200 |      32.799µs |    192.168.1.17 | GET      "/web/desktop.html"
[GIN] 2023/07/20 - 11:54:26 | 200 |      60.278µs |    192.168.1.17 | GET      "/web/css/style.css"
[GIN] 2023/07/20 - 11:54:26 | 200 |      11.364µs |    192.168.1.17 | GET      "/web/css/desktop.css"
[GIN] 2023/07/20 - 11:54:26 | 404 |       4.996µs |    192.168.1.17 | GET      "/web/dist/ts/theme_loader.js"
[GIN] 2023/07/20 - 11:54:26 | 200 |      28.396µs |    192.168.1.17 | GET      "/web/css/winbox.min.css"
[GIN] 2023/07/20 - 11:54:26 | 200 |      54.063µs |    192.168.1.17 | GET      "/web/js/winbox.min.js"
[GIN] 2023/07/20 - 11:54:26 | 404 |       4.474µs |    192.168.1.17 | GET      "/web/dist/ts/desktop.js"
[GIN] 2023/07/20 - 11:54:26 | 404 |       8.296µs |    192.168.1.17 | GET      "/web/dist/ts/easteregg.js"
[GIN] 2023/07/20 - 11:54:26 | 200 |     916.186µs |    192.168.1.17 | GET      "/web/images/seekr-transparent.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |      59.056µs |    192.168.1.17 | GET      "/web/images/blockexplorerone.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |     873.102µs |    192.168.1.17 | GET      "/web/images/whois.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |    2.681256ms |    192.168.1.17 | GET      "/web/images/seekr-icon.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |      61.948µs |    192.168.1.17 | GET      "/web/images/settings.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |    7.196764ms |    192.168.1.17 | GET      "/web/images/guide.png"
[GIN] 2023/07/20 - 11:54:26 | 200 |      7.2304ms |    192.168.1.17 | GET      "/web/images/crtsh.png"
[GIN] 2023/07/20 - 11:54:27 | 200 |      56.477µs |    192.168.1.17 | GET      "/web/images/favicon.ico"`

After further inspection, it seems the /web/dist directory is non existent on my machine.

**Comment by Niteletsplay** [comment]
I think you need to compile TypeScript and run some go command.
@9glenda should be able to help

I will later update the wiki to include more details about setting it up

**Comment by anoo2niem** [comment]
Hey, 

After additionally installing TypeScript, and running both commands, everything is working now.

Thanks again!

Have a great day

**Comment by Niteletsplay** [comment]
Awesome! Just open another issue if you encounter any additional problems
