### ISSUE TITLE
[Website] Themes mess with crt.sh css

### ISSUE THREAD

**Issue by 9glenda** [seekr-osint/seekr#529]
The background changes as expected but the font stays black making dark themes unusable. Just change the css for the font of crt.sh too then it also looks good.

**Comment by Niteletsplay** [comment]
crt.sh has no background-color property set, which makes it transparent.
Theres 2 options:

1.  Manually set background color to white (like original page)
2.  Add theme color, specifically to crt.sh background

**Comment by Niteletsplay** [comment]
I cant change the iframes css (otherwise its way too complicated and uses CORS stuff).
I can however change the color of the specific window background.
