### ISSUE TITLE
[Website] Code Translation completely sucks (it's worse then pizza theme)

### ISSUE THREAD

**Issue by 9glenda** [seekr-osint/seekr#548]
The translation code not only drives me crazy causing issues with drop downs and all kind of thing's it's also really bad on performance and gives me horrible loading times. A much saner approach to translating would be to not replace the whole ui from English to another language all the time but instead to create elements in the selected language and never replace anything.

The 2 main reasons why I hate the translation code are:
1. My PC can barely handle loading seekr under 2 seconds
2. It causes issues with my current PR due to the core design of it.

**Comment by Niteletsplay** [comment]
Removed translation
