### ISSUE TITLE
[WEBSITE] use htmx backend rendered

### ISSUE THREAD

**Issue by 9glenda** [seekr-osint/seekr#636]
I hate ts I will never use it again.

**Comment by Niteletsplay** [comment]
This is kinda unnesecary for now

**Comment by Niteletsplay** [comment]
However we could try using svelte, react or angular in frontend or maybe templatize everything so we can do like <chip class="btn bottom-right"></chip> instead of the current impl

**Comment by Niteletsplay** [comment]
> > However we could try using svelte, react or angular in frontend or maybe templatize everything so we can do like instead of the current impl
> 
> But this will still rub into my main issue with js. State is messed up all over the place. 

You dont have to look at it lol

**Comment by Niteletsplay** [comment]
Also a js framework will require a rewrite anyway, since they have solutions for global vars
